### ISSUE TITLE
Network units state reported as offline after some time

### ISSUE THREAD

**Issue by nils-hde** [hellqvio86/home_assistant_casambi#24]
I have provided some logs and more detailed information in https://github.com/hellqvio86/home_assistant_casambi/issues/20#issuecomment-846373378

Related to #3

**Comment by hellqvio86** [comment]
Offline state is reported by the casambi side, so it's probably a websocket message that the home assistant (aiocasambi side doesn't understand) or something similar.

**Comment by hellqvio86** [comment]
The api is reporting that your unit is offline, this is from the Casambi cloud API side:
2021-05-20 07:32:23 DEBUG (MainThread) [aiocasambi.controller] get_network_state response: {'dimLevel': 0.4627450980392157, 'activeScenes': [], 'id': '<REMOVED_NETWORK_ID>', 'revision': 14, 'grade': 'EVOLUTION', 'address': '78a15f649b5f', 'name': 'Home', 'type': 'PROTECTED', 'timezone': 'Europe/Berlin', 'gateway': {'name': '<REMOVED_PERSON_NAME>s G5'}, 'units': {'1': {'priority': 3, 'on': False, **'online': False,** 'condition': 0, 'status': 'ok', 'activeSceneId': 0, 'controls': [[{'type': 'Dimmer', 'value': 0.0}, {'type': 'Vertical', 'value': 0.9254901960784314}, {'min': 2700, 'max': 4000, 'level': 0.8153846153846154, 'type': 'CCT', 'value': 3760.0}]], 'dimLevel': 0.4627450980392157, 'id': 1, 'address': '<REMOVED_UNIT_ADDRESS>', 'name': 'Mito sospeso', 'firmwareVersion': '33.0', 'position': 0, 'fixtureId': 3098, 'groupId': 0, 'type': 'Luminaire'}}, 'photos': [], 'scenes': {}, 'groups': {}}

That's why the unit is marked offline

**Comment by nils-hde** [comment]
Hm yes I figured that, thanks. 

Actually the part that confused me is why turn_on light service does not work if it is reported offline here whereas the Homebridge Extension manages to bring it back online anyways?

https://github.com/awahlig/homebridge-casambi

Maybe contacting the maintainer of it will help

**Comment by hellqvio86** [comment]
Its not working because the device is disabled, of-course that could be disabled, but that's the intended behavior.

"Waking up" units has been up before: https://github.com/hellqvio86/home_assistant_casambi/issues/10 and its sadly not supported, but disabling the disable mechanism and sending turn_on_light would probably yield the same result.

**Comment by nils-hde** [comment]
Is it possible to disable the mechanism in the config? Or could you refer me to the part of the code that handles this otherwise?

**Comment by hellqvio86** [comment]
Its not possible right now without changing the homeassistant side (it checks the aiocasambi unit state), this is the same mechanism that handles network issues (devices gets disabled when a network issue gets detected). And that is probably something that users wants 🙂

So what is needed is to separate network issues and unit wake up issues.

The code base is using both pull and push, the log messages it from a pull to the http api, so hopefully casambi api correct it self's and reports the unit as "online" if it is, I think it its on a 60 seconds timer, the pull that is and that is possible to decrease, that could "fix" your issues. 

But the timer is pretty aggressive as is, so I would not set it lower myself, then casambi might complain on there side 😉🙂

**Comment by hellqvio86** [comment]
One way of forcing a turn_on_light even if a device is disabled could probably be to implement a custom service https://community.home-assistant.io/t/registering-a-service/40327/8

But that's a stretch and really not the "intended way" of implementing a light in home assistant 🙂

**Comment by robsonke** [comment]
It's the most annoying problem I still face. By coincidence I checked the availability of this local device: https://casambi.lithernet.de
But after a bit of emailing around, they gave me a price of 790 euro excl shipping. Which is quite ridiculous for a fancy ethernet -> bluetooth adapter.

**Comment by hellqvio86** [comment]
I have heard that some Swedes use local dali gateway with dali integration for Casambi, the prices is ridiculous and its way to complex (for me).

**Comment by hellqvio86** [comment]
Closing this issue, wake up is something that Casambi needs to support on there end, we tested different wake up strategies in #10 with no success. Please reach out to Casambi with a feature request, so they know that wake up is of interest to the Casambi dev community.
