### ISSUE TITLE
Issue with distribution/vertical on an Oligo Grace 

### ISSUE THREAD

**Issue by weinberger** [hellqvio86/home_assistant_casambi#53]
**Describe the bug**

I have a ch4 device with distribution/vertical support. If I try to adjust distribution with the given service, nothing happens.

**To Reproduce**

**Expected behavior**

The light should be distributed between the upper and lower light.

**Debug logs**
See attachment

**Screenshots**

**Platform information (please complete the following information):**

 - OS: iOS 15.7.1
 - Home assistant version:
   - Home Assistant Supervisor: 2022.10.0
   - Home Assistant Core: 2022.10.5
   - Home Assistant Operating System: 9.3

**Additional context**

**Comment by weinberger** [comment]
[OligoGrace.txt](https://github.com/hellqvio86/home_assistant_casambi/files/9890107/OligoGrace.txt)

**Comment by hellqvio86** [comment]
aiocasambi is saying that your lights does not support distribution:
`supports_brightness=True supports_distribution=False`

aiocasambi looks if **Vertical** is set in the controls and in your case it isn't, here is what your light supports:
`2022-10-28 18:03:36.168 DEBUG (MainThread) [aiocasambi.websocket] websocket recived msg.type: aiohttp.WSMsgType.BINARY data: {'address': '25561891109f', 'controls': [{'name': 'dimmer0', 'type': 'Dimmer', 'value': 0.0}, {'name': 'dimmer1', 'type': 'Dimmer', 'value': 0.0}, {'min': 2200, 'max': 5000, 'level': 0.18214285714285713, 'name': 'temperature', 'type': 'CCT', 'value': 2710.0}], 'method': 'unitChanged', 'fixtureId': 22602, 'priority': 3.0, 'condition': 0.0, 'wire': 78, 'activeSceneId': 0, 'sensors': {}, 'name': 'GRACE Window', 'online': True, 'details': {'OEM': 'OLIGO', 'fixture_model': 'GRACE PL HA TW'}, 'id': 3, 'dimLevel': 0.0, 'status': 'ok'}`

Here is what the cloud api is saying about your controls (from the data above):
`'controls': [{'name': 'dimmer0', 'type': 'Dimmer', 'value': 0.0}, {'name': 'dimmer1', 'type': 'Dimmer', 'value': 0.0}, {'min': 2200, 'max': 5000, 'level': 0.18214285714285713, 'name': 'temperature', 'type': 'CCT', 'value': 2710.0}]`

**Comment by hellqvio86** [comment]
What you have in your light is two dimmers and that can't aiocasambi handle:
`2022-10-28 18:03:43.105 DEBUG (MainThread) [aiocasambi.unit] unit_id=2 - setter controls - Adding following control to controls: {'name': 'dimmer0', 'type': 'Dimmer', 'value': 0.4392156862745098}
2022-10-28 18:03:43.105 DEBUG (MainThread) [aiocasambi.unit] unit_id=2 - setter controls - Adding following control to controls: {'name': 'dimmer1', 'type': 'Dimmer', 'value': 0.4392156862745098}`

Those two dimmers probably control the lights, so Home assistant (the integration) should probably handle this lights as two different light sources and aiocasambi needs to be able to handle multiple dimmers.

I myself probably need hardware for implementing this, debugging it while I adapt the code.

But the first step is to test the hypothesis and see if its right, play around with the api and see if it works.

Easiest is probably probably to send a craftet control message through **set_unit_target_controls** in https://github.com/hellqvio86/aiocasambi or **set_unit_target_controls** in [casambi](https://github.com/hellqvio86/casambi) and see if it works.

https://github.com/hellqvio86/casambi is easiest to adapt since its not async.

You can dimm a Casambi light by setting control to:
`target_controls={"Dimmer0": {"value": 0.5}, {"Dimmer1": {"value": 0.2}}`
for example and see if that works.

**Comment by hellqvio86** [comment]
Added this device to the readme as unsupported, I can revisit it when I have hardware with two dimmers
