### ISSUE TITLE
EnOcean battery less controllers integration

### ISSUE THREAD

**Issue by Superkikim** [hellqvio86/home_assistant_casambi#88]
Hi guys. Thx for the great work.

I have bought Feller EnOcean 4 channel switchs for my Casambi implementation. Works perfectly with the Casambi cloud. 

Since last version of the integration, they are now integrated as sensors rather than light. This is a progress. 

If you could have them configured as trigger devices it would be perfect. 

As a reference, you can check the Feller EnOcean 4 channels integration for HUE which works perfectly. 

https://github.com/home-assistant/core/blob/dev/homeassistant/components/hue/device_trigger.py

I'd love to participate, but I have to say, despite my scripting skills and experience, I'm lost in developing integrations at the moment :(

If you need anything (logs, hardware details, anything else), let me know. I'll gladly share and participate to my skill limits.

**Comment by hellqvio86** [comment]
Please provide debug logs, in general I can't support device types that I don't have physical access to, need it for developing support for it and I will not develop support for device types in the blind, its just a hobby project. That say other people besides me might want to.

You see the device since the integration now adds a binary sensor telling you if the Casambi unit is connected or not to the api.

**Comment by hellqvio86** [comment]
Closing this issue since Casambi isn't supporting the use case through the cloud api which this integration is based on.
